### ISSUE TITLE
xhs的发布以及其他平台的发布，有时会没有播放量的问题

### ISSUE THREAD

**Issue by Jacky-Chiu** [dreammis/social-auto-upload#13]
有时播放量是0

**Comment by dreammis** [comment]
我运行了1年多，也出现过0播放的问题
但是问题并不是上传机制的问题，因为大量有播放的，问题更多还是视频质量、或者原创性的问题

![微信图片_20240531111906](https://github.com/dreammis/social-auto-upload/assets/12542216/5b8b9007-05be-401c-969e-a4a94572d103)

**Comment by Jacky-Chiu** [comment]
> 我运行了1年多，也出现过0播放的问题 但是问题并不是上传机制的问题，因为大量有播放的，问题更多还是视频质量、或者原创性的问题
> 
> ![微信图片_20240531111906](https://private-user-images.githubusercontent.com/12542216/335434659-5b8b9007-05be-401c-969e-a4a94572d103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjYwMjMsIm5iZiI6MTcxNzEyNTcyMywicGF0aCI6Ii8xMjU0MjIxNi8zMzU0MzQ2NTktNWI4YjkwMDctMDViZS00MDFjLTk2OWUtYTRhOTQ1NzJkMTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAzMjIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OWY5N2ZkY2VjZDk0MWM5YmNlY2I3OTU4MTNiNzdkZGM3OGM4ZDJjYTU5YmZkZDk3MjI3NTJlMmNhYmZkNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oe6hVR7up63Mg6EjEl1R7IXVZ2oqSJaOhUjhLLm2KhY)

xhs呢？我主要是xhs有这个问题

**Comment by Jacky-Chiu** [comment]
@dreammis xhs呢？我主要是xhs有这个问题，你有遇到吗？

**Comment by dreammis** [comment]
我是有遇到过0播放的
但是相同类型的视频，大部分呢又有播放，这就排除了上传的因素。
我只能告诉你，不是上传这部分导致的0播放。
