### ISSUE TITLE
小红书发布的tag没生效

### ISSUE THREAD

**Issue by qingchensan** [dreammis/social-auto-upload#15]
![screenshot-20240612-161524](https://github.com/dreammis/social-auto-upload/assets/16078743/9a11c36c-a05d-44cc-8c91-dfa2b3a55c74)
如图：最后一个高亮的tag(#短视频)是我在编辑模式下添加的

**Comment by baiyibing123** [comment]
Cookie咋获取的，为啥我导出的没有示例的内容

**Comment by dreammis** [comment]
> ![screenshot-20240612-161524](https://private-user-images.githubusercontent.com/16078743/338879773-9a11c36c-a05d-44cc-8c91-dfa2b3a55c74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDkwNTUsIm5iZiI6MTcxODIwODc1NSwicGF0aCI6Ii8xNjA3ODc0My8zMzg4Nzk3NzMtOWExMWMzNmMtYTA1ZC00NGNjLThjOTEtZGZhMmIzYTU1Yzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE2MTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMzEyMDJkOTJjZDYzNGViZjYyZTRkYTQxMjM3Y2ZiNmY2MDUxMmFiNGIzNGM2NGNmOWFlNDJiOWJiM2MxNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lNeXHnSdqpJbadVUcZRQ_HTk3lyI6Wp26hbTbaRqYtI) 如图：最后一个高亮的tag(#短视频)是我在编辑模式下添加的

已修复。之前都没注意到。

**Comment by dreammis** [comment]
> Cookie咋获取的，为啥我导出的没有示例的内容

看下格式

**Comment by dreammis** [comment]
该问题已修复，关闭了
