### ISSUE TITLE
抖音定时发布好像不太行了

### ISSUE THREAD

**Issue by lurongkang123** [dreammis/social-auto-upload#17]
抖音定时发布好像不太行了，清空输入框之后会自动填，导致后面填的值无效

**Comment by dreammis** [comment]
我试了下是ok的，我把去除地理位置的部分给删掉了。

**Comment by dreammis** [comment]
是不是我们浏览器不一样，我是conf设置了本地的chrome。你们也是这样吗？

**Comment by dreammis** [comment]
未见后续反馈

**Comment by wuula** [comment]
> 我这好像也是不行，我改了一下代码，大体的逻辑是：先将光标移动到最后，向前删除15次，保留2，因为全清空会导致恢复，然后填充024-xx-xx xx：xx 因为整个项目我都做了改造，所以就不贴全部代码了，大家直接套应该会出问题，思路可供参考
> 
> await page.locator('.semi-input[placeholder="日期和时间"]').click() await page.keyboard.press("End") for i in range(15): await page.keyboard.press("Backspace",delay=50) await page.keyboard.type(publish_date[1:],delay=100) await page.keyboard.press("Enter")

这个可以，感谢大佬，也感谢原作者大佬~
