### ISSUE TITLE
b站上传失败

### ISSUE THREAD

**Issue by z2p** [dreammis/social-auto-upload#19]
z2p@MacBook-Pro social-auto-upload$ python3 upload_video_to_bilibili.py 
视频文件名：/Users/z2p/Downloads/social-auto-upload/videos/测试1.mp4
标题：测试 🥺❤️‍🩹🍴
Hashtag：['123', 'aaa']
使用cookies上传
probe_version=20221109&upcdn=tx&zone=cs 0.24969190599222202
probe_version=20221109&upcdn=bda2&zone=cs 0.25500661200203467
probe_version=20221109&upcdn=bldsa&zone=cs 0.06020553699636366
retry chunk0 >> 1. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 2. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 3. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 4. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 5. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 6. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 7. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 8. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 9. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
retry chunk0 >> 10. Cannot connect to host upos-cs-upcdnbldsa.bilivideo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

**Comment by dreammis** [comment]
网络问题，重试下。尝试关闭代理等

**Comment by z2p** [comment]
> 网络问题，重试下。尝试关闭代理等

试了不行，使用biliup就可以上传，douyin和tencent也都可以正常

**Comment by dreammis** [comment]
我试了下，我这里是ok的。看这个错误似乎是证书的问题，你可以尝试更新下这个库试试看：certifi

**Comment by z2p** [comment]
> 我试了下，我这里是ok的。看这个错误似乎是证书的问题，你可以尝试更新下这个库试试看：certifi

我debug了一下，主要是/biliup/plugins/bili_webup.py里upload_chunk使用的aiohttp.client.session出现了证书错误，比较奇怪其他地方都没出问题，加了一个ssl=False就可以了
