### ISSUE TITLE
disable Scheduled 

### ISSUE THREAD

**Issue by jbosolutions** [dreammis/social-auto-upload#28]
hey! how can i disable Scheduled ? i need to publish inmediatly.

**Comment by jbosolutions** [comment]
@dreammis

**Comment by dreammis** [comment]
you mean tiktok?
if the set `publish_date ` to 0, then publish immediately

**Comment by jbosolutions** [comment]
Thank you brother, do you have telegram or any chat? We can help with all
this. Thanks.

--------------------------------------------------------------------------------------------------------------------------------------------------

Julián Blet

<https://www.freelancer.com/affiliates/email/4374309/>

Trusted Software | Diseño Web - Sistemas - Diseño Gráfico - Producción
Publicitaria

*WHATSAPP 24/7:* (+54)3512693336

*E: ***@***.*** ***@***.***>*
*A: Argentina-*

 Córdoba.

-------------------------------------------------------------------------------------------------------------------------------------------------

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. JBOSolutions is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by jbosolutions** [comment]
I can’t find where is
publish_date
what line and file for TikTok?

--------------------------------------------------------------------------------------------------------------------------------------------------

Julián Blet

<https://www.freelancer.com/affiliates/email/4374309/>

Trusted Software | Diseño Web - Sistemas - Diseño Gráfico - Producción
Publicitaria

*WHATSAPP 24/7:* (+54)3512693336

*E: ***@***.*** ***@***.***>*
*A: Argentina-*

 Córdoba.

-------------------------------------------------------------------------------------------------------------------------------------------------

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. JBOSolutions is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by jbosolutions** [comment]
hmmm i cant find it, i changed some lines to 0 but didnt worked...

**Comment by jbosolutions** [comment]
@dreammis  
hmmm i cant find it, i changed some lines to 0 but didnt worked...

**Comment by jbosolutions** [comment]
oh i found it

Change lines of upload_video_to_tiktok.py

# LINES 16 AND  23

publish_datetimes = [0] * file_num

app = TiktokVideo(title, file, tags, publish_datetimes[index], account_file)

**Comment by dreammis** [comment]
happy to see you run it successful.
