### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by jbosolutions** [dreammis/social-auto-upload#29]
Hey bro can I ask you where can I change the thumbnails moment? I mean when it should make the screenshot of the video

**Comment by jbosolutions** [comment]
@dreammis

**Comment by dreammis** [comment]
now the repo don't support change thumbnails, the tk will the first frame from the video as the thumbnails.
I will support thumbnails later.

**Comment by dreammis** [comment]
now, supoort thumbnail, change it to chrome.
pull the new repo
read the new README
if has any question tell me.
