### ISSUE TITLE
not working now

### ISSUE THREAD

**Issue by jbosolutions** [dreammis/social-auto-upload#32]
hey bro... now it doesnt works anymore.. 

Error al subir video: Page.wait_for_selector: Timeout 30000ms exceeded.
Call log:
waiting for locator("iframe[data-tt=\"Upload_index_iframe\"]") to be visible

**Comment by dreammis** [comment]
update the rep, try it again. tell me if is ok.

**Comment by dreammis** [comment]
not seen any reply, close.

**Comment by jbosolutions** [comment]
@dreammis hello, it is not clicking on the UPLOAD popup button:


 -   <div dir="ltr" class="TUXModal-overlay" data-transiti…>…</div> from <div id=":r1p:" data-floating-ui-portal="">…</div> subtree intercepts pointer events
  - retrying click action, attempt #57
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   <div dir="ltr" class="TUXModal-overlay" data-transiti…>…</div> from <div id=":r1p:" data-floating-ui-portal="">…</div> subtree intercepts pointer events
  - retrying click action, attempt #58
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   <div dir="ltr" class="TUXModal-overlay" data-transiti…>…</div> from <div id=":r1p:" data-floating-ui-portal="">…</div> subtree intercepts pointer events
  - retrying click action, attempt #59
  -   waiting 500ms

2024-07-12 04:55:52 | INFO:   [-] video publishing

**Comment by jbosolutions** [comment]
it is scrolling up down up down left right etc... but not clicking.. why?

**Comment by jbosolutions** [comment]
ohh.. now i see it uploaded the video... but windows is not closing... just keeping a loop

**Comment by dreammis** [comment]
😅
is anything wrong I can help now?

**Comment by jbosolutions** [comment]
Yes the last comment I put 🤣
