### ISSUE TITLE
抖音发布同步西瓜一栏，因为元素定位失败，无法勾选原创按钮

### ISSUE THREAD

**Issue by JiahuaLink** [dreammis/social-auto-upload#34]
我想勾选一下原创按钮，参与中视频计划，但是一直不成功，按钮切换前点击会报错开关是禁用的disable的

**Comment by dreammis** [comment]
先手动开启和绑定西瓜视频。否则，会出现意想不到的情况

程序并没判断你到底开没开西瓜视频
