### ISSUE TITLE
关于如果cookies失效会怎样的咨询

### ISSUE THREAD

**Issue by heartInsert** [dreammis/social-auto-upload#46]
作者您好，我已经成功运行了并看了您关于抖音上传的代码，毕竟这是一个自动化项目，我想问下如果某天我的抖音cookies突然过期了，按现在的逻辑是会一直卡在扫码登录的界面吗，我的理解是否正确,   我不希望它退出，现在是会这样吗

**Comment by dreammis** [comment]
douyin_setup是来判断，是否cookie过期，如果过期你别让后续执行就好了

**Comment by heartInsert** [comment]
懂了，6666

**Comment by dreammis** [comment]
自己可以写个程序，定期检测下cookie是否有效。以备不时之需
