### ISSUE TITLE
登录有时出现的验证码能通过吗？

### ISSUE THREAD

**Issue by terranc** [dreammis/social-auto-upload#52]

**Comment by dreammis** [comment]
哪个平台，不同平台验证码不一样。可以用三方的付费平台试一试

**Comment by terranc** [comment]
> 哪个平台，不同平台验证码不一样。可以用三方的付费平台试一试

有什么三方付费平台推荐吗？ @dreammis

**Comment by dreammis** [comment]
我没试过哎，[Capsolver](https://www.capsolver.com/)这个网站，好像类似的还蛮多的
