### ISSUE TITLE
登录遇到问题

### ISSUE THREAD

**Issue by heartInsert** [dreammis/social-auto-upload#53]
本来一直能用，用了很久了，突然不行了
![image](https://github.com/user-attachments/assets/d17dfebf-c605-40c9-b5f1-ae506a60dfd9)
登录超时了，30000ms 也就是30秒已经挺长了，但是超时有点奇怪。然后我直接在浏览器输入 [https://creator.douyin.com/creator-micro/content/upload](url)  能打开我的抖音页面没有任何问题。然后还有点奇怪的是程序运行过程中chrome一直没有出现。我的本地默认浏览器是chrome。

![image](https://github.com/user-attachments/assets/ed5d552a-f42d-4c63-9e5e-f5844da5f513)

应该就是这导致的，有点奇怪

**Comment by dreammis** [comment]
更新代码试试

**Comment by heartInsert** [comment]
破案了，网络问题，这校园网加载个页面半天加载不出来

**Comment by dreammis** [comment]
🆗
