### ISSUE TITLE
登录小红书总是报错

### ISSUE THREAD

**Issue by Monster-zero** [dreammis/social-auto-upload#57]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=11901): Max retries exceeded with url: /sign (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025094000CB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by dreammis** [comment]
我不知道你调用哪个程序，你无意间采用的是server的模式，这种适用于多账号。建议你直接先example试下，再研究里面其他的用法
