### ISSUE TITLE
小红书提示无登录信息，cookie获取没有问题，签名没有问题

### ISSUE THREAD

**Issue by cugb1004101218** [dreammis/social-auto-upload#61]
xhs.exception.DataFetchError: {'code': -100, 'data': {}, 'msg': '无登录信息', 'success': False}

**Comment by dreammis** [comment]
你需要 xiaohongshu 客户端页面登录，以及creator 后台都登录后，才会ok
似乎两者权限不同

**Comment by dqmmpb** [comment]
是的，要通过小红书的首页登录，然后跳转到creator后台，才会ok。看上去是从首页登录后cookie中保存了一些其他信息。只通过creator后台登录是会提示上述错误的。但如果从首页登录，会导致其他浏览器打开的相同账号被踢出去（ps： 但打开的creator后台还是可以刷新的）
