### ISSUE TITLE
抖音上传视频页面出现异常div块导致自动化中断

### ISSUE THREAD

**Issue by xander-wang** [dreammis/social-auto-upload#66]
很奇怪，今天才出现的，难道是官方的反bot机制吗
![stlkk1mq phj](https://github.com/user-attachments/assets/bf18a3eb-7135-4f4a-a5fe-e40dee3cf42e)

**Comment by dreammis** [comment]
我之前也遇到过，没理睬。
不是这个导致的，是因为，判断上传与否的条件改了，导致上传成功，程序没得到正确的判断，卡住了

我改了下，可以试试。

**Comment by youngcube** [comment]
word word word 应该是 fingerprintjs 用于检查字体宽度，进而检查浏览器的。

https://github.com/fingerprintjs/fingerprintjs/blob/3e6bd9872be125ec10dcf6a57b2366c04c4f2bd0/src/sources/font_preferences.ts#L158

应该可以看到页面上还有 `mmMwWLliI0fiflO&1`。也是 fingerprintjs 包含的逻辑。

但不确定为什么只有 playwright 打开才会有，抛砖引玉一下。

**Comment by xander-wang** [comment]
学习了
