### ISSUE TITLE
抖音上传页面出现乱码导致上传失败

### ISSUE THREAD

**Issue by zaojue405** [dreammis/social-auto-upload#67]
![image](https://github.com/user-attachments/assets/7d2f6777-e780-43ce-8b33-8c3e9177498d)
用了一段时间后突然出现这些字，然后就上传不了了

**Comment by Buluseng** [comment]
不是这里出问题了，更新一下代码可以 用

**Comment by dreammis** [comment]
暂时不影响主功能使用，关闭了
