### ISSUE TITLE
按照对应获取cookie的方法， 但是还是登录不上，不知道怎么回事

### ISSUE THREAD

**Issue by im2058** [dreammis/social-auto-upload#7]
![image](https://github.com/dreammis/social-auto-upload/assets/30195987/00ee8f28-377a-447b-97ee-ca935c3c876b)

如上accounts.ini和 运行后的error。

**Comment by im2058** [comment]
![image](https://github.com/dreammis/social-auto-upload/assets/30195987/e5549ba3-82e3-46f5-91e7-cb9c87435ab2)

**Comment by dreammis** [comment]
不好意思啊，过年没时间解决，另外我自己放弃小红书了，审核奇葩。
如果比较着急，可以尝试从这个库来寻找答案：https://github.com/ReaJason/xhs

**Comment by dreammis** [comment]
看样子是你cookie问题，参照正常的cookie是什么样的
![5985bb10480163bc723e69c8cca886c](https://github.com/dreammis/social-auto-upload/assets/12542216/09443c55-e19d-4b0a-a713-e9ba50b96738)
